apiVersion: v1
kind: Pod
metadata:
  labels:
    app: webserver
  name:  app
spec:
  containers:
    - name: app
      image: 329921743825.dkr.ecr.us-east-1.amazonaws.com/myapp:v3.0
      ports:
        - containerPort: 8080
          protocol: TCP
      env:
        - name: DBHOST
          value: "mysql.assignment2.svc.cluster.local"
        - name: DBUSER
          value: "root"
        - name: DBPWD
          value: "dbpwd"
        - name: DBPORT